const messages = [
  "Birine sabah kahvesi ısmarla.",
  "Birine içten bir teşekkür et.",
  "Yolda zorlanan birine yardım et.",
  "Sokakta bir hayvana su ver.",
  "Çalışma arkadaşına moral ver.",
  "Birine sevdiği bir şarkıyı hediye et.",
  "Bir arkadaşına gülümse ve selam ver.",
  "Birine sabah selamı gönder.",
  "Birisine güzel bir hikaye anlat.",
  "Birine cesaret ver ve destek ol.",
  "Birine günün güzel geçmesi için dua et.",
  "Birine sıcak bir içecek ısmarla.",
  "Birine işinde başarı dile.",
  "Birine teşekkür et ve ona değer verdiğini hissettir.",
  "Birisine yardım et ve zaman ayır.",
  "Birine hedeflerine ulaşabilmesi için cesaret ver.",
  "Birine moral vererek hayatına dokun.",
  "Zihnini rahatlatacak bir öneri sun.",
  "Birine duygusal destek ver.",
  "Birine küçük bir hediye al.",
  "Birine güzel bir mesaj yaz.",
  "Birine motivasyon ver ve ona güç kat.",
  "Birine sosyal desteğini hissettir.",
  "Birine anlamlı bir mesaj gönder.",
  "Birine hatırlatıcı bir not bırak.",
  "Birine destek olabilecek küçük bir yardımda bulun.",
  "Birine güzel bir söz söyle.",
  "Birine teşekkür etmek için küçük bir jest yap.",
  "Birine bir kitap öner.",
  "Birine pozitif enerji gönder.",
  "Birine günlük ihtiyaçlarını karşılamasında yardımcı ol.",
  "Birine moral verici bir jest yap.",
  "Birine işini kolaylaştıracak bir teklif yap.",
  "Birine zor zamanında destek ol.",
  "Birine cesaretini artıracak bir söz söyle.",
  "Birine güçlü kalması için ilham ver.",
  "Birine zor bir konuda yardımcı ol.",
  "Birine moral kaynağı ol.",
  "Birine zorlanırken yardım et.",
  "Birine elinden gelenin en iyisini yapması için cesaret ver.",
  "Birine güçlü durması için motivasyon ver.",
  "Birine içsel gücünü hatırlat.",
  "Birine sevdiği bir şeyi al ve onu mutlu et.",
  "Birine güvendiğini ve değerli olduğunu hatırlat.",
  "Birine anlamlı bir hediye ver.",
  "Birine hayatın güzel olduğunu hatırlat.",
  "Birine eğlenceli bir şeyler öner.",
  "Birine küçük bir iyilik yaparak gününü güzelleştir.",
  "Birine eski bir dost gibi yaklaş ve destek ol.",
  "Birine sabır göster.",
  "Birine zor bir durumda olduğunda destek ol.",
  "Birine kıymetli bir şey öğreterek yardım et.",
  "Birine güvendiğini söyle.",
  "Birine değerini hissettirecek bir şey yap.",
  "Birine zor bir durumdan çıkmasına yardımcı ol.",
  "Birine güven aşılayacak bir şey söyle.",
  "Birine samimi bir iltifat et.",
  "Birine teşekkür et ve sana kattığı değerleri takdir et.",
  "Birine gülümsemeni gönder.",
  "Birine moral kaynağı olacak bir mesaj gönder.",
  "Birine özel bir hediye ver.",
  "Birine günün güzel geçmesini dileyerek moral ver.",
  "Birine işin stresinden uzaklaşması için önerilerde bulun."
];

function showRandomMessage() {
  const randomIndex = Math.floor(Math.random() * messages.length);
  const message = messages[randomIndex];
  document.getElementById("message").textContent = message;
}
